# Check the documentation at https://goreleaser.com

# Commented out because it's a security risk (https://go.dev/blog/supply-chain).
# before:
#   hooks:
#     - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
    main: ./cmd/checkip/checkip.go
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
