name: test, scan and release

on:
  pull_request:
    branches:
      - master
  push:
    tags:
      - "v*"

jobs:
  go-test:
    uses: jreisinger/github-actions/.github/workflows/go-test.yml@v1.0.1
  trivy-scan:
    uses: jreisinger/github-actions/.github/workflows/trivy-scan.yml@v1.0.1
  go-release:
    needs:
      - go-test
      - trivy-scan
    uses: jreisinger/github-actions/.github/workflows/go-release.yml@v1.0.1
